### ISSUE TITLE
Tiers

### ISSUE THREAD

**Issue by Butterruler** [Duprs/Duprs-Revival#11]
**What is your feature?**
A clear and concise description of what your feature is

When a new player joins they can level up and each level has a tier. Tiers can consist of items, ranks, special boosts, and much more

**What platform is this for?**
Example: Discord, Minecraft, etc.

Minecraft
**Detailed explaination**
Give a detailed rundown of what this feature should do

It should give new players a way to stay active on completing certain challenges to level up in tiers

**Why should this be added?**
Give a rundown of what the purpose of this feature is, and who it will benefit

It can make players more active and make the server more fun. It will benefit the players and who stays active.

**Additional content**
Include any supportive text or imagery so that we can better understand your feature [optional]

Add better things in the higher tiers so people grind for it. The challenge should be easy in the beginning and harder at the end of the tiers. Each season the tier lis resets.

**Comment by Echological** [comment]
similar to #5

**Comment by Butterruler** [comment]
I see, my bad then
