### ISSUE TITLE
Issue with random items

### ISSUE THREAD

**Issue by Scope2252** [Duprs/Duprs-Revival#15]
The random items bugs out quite often. One example is when you are on and it is working, then someone joins, it practically trades off priority to the toggle and the person who most recently joined gets to have toggle and nobody else. Another issue, is when you have this priority of the random item toggle, it may give you 3 or 2 items at a time instead of one. The specific issue I'm trying to get at is when the server starts and one person is in it, everything is normal, 1 item each 10-15 seconds and what not, and when someone joins everything gets ruined and the issues stated above occur.

**Comment by Echological** [comment]
we already talked about this

**Comment by Echological** [comment]
however, i just pushed an update that seems to fix it, let me know if there are any other problems!
