### ISSUE TITLE
Unique items

### ISSUE THREAD

**Issue by ElmoPog** [Duprs/Duprs-Revival#5]
**What is your feature?**
Undupeable items

**What platform is this for?**
Minecraft

**Detailed explaination**
Items that can only be obtained in certain ways like achievements. They should be undupeable and have a special power like a teleport bow (bad example but you get the point)

**Why should this be added?**
It makes people actually grind for a certain item and they could flex with it as its not dupeable

**Additional content**
It’s sad no-ones suggesting stuff after the hard work on it, keep going <3

**Comment by B4ssouli** [comment]
That's actually a really good idea! We will consider adding it 👍.

**Comment by Echological** [comment]
As referenced in #11 and #10, we could have a tiering system that uses xp levels or we could make some other leveling system to track a system.

I don't know how plausible a system of unique items will be for the server, however, we could eventually look into this.

**Comment by Echological** [comment]
I don't think we will be going forward with this idea for the flow of the server
