### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by ElmoPog** [Duprs/Duprs-Revival#8]
**What is your feature?**
A tradable currency that can be obtained in several ways

**What platform is this for?**
Minecraft

**Detailed explaination**
Essentially, what it would be is smt like dupr coins which can be spent in a special shop. U can for example buy a dupe token which allows u to get a copy of an undupable item, you can only get 1 extra of that item and not literally dupe it in quantity. You would only be able to dupe it without it’s existing upgrades. U could trade this extra item then for example. Or these coins would allow u to buy upgrades on the undupeable items as suggested in my first suggestion. 

**Why should this be added?**
It adds something to the undupeable items for upgrades and still somewhat of a way to easily get more of it. Upgrades for such items would seem logical as they are not meant to be increased in quantity easily.

**Additional content**
<3

**Comment by Echological** [comment]
coins have been implemented
